Main object
===========

``wig.wig`` object
------------------

.. autoclass:: wig.wig.wig
    :members:
    :member-order: bysource

Input Deck Creation Submodules
==============================

wig.geo object
--------------

.. autoclass:: wig.geo.geo
    :members:
    :member-order: bysource

wig.matl object
---------------

.. autoclass:: wig.matl.matl
    :members:
    :member-order: bysource

wig.cell object
---------------

.. autoclass:: wig.cell.cell
    :members:
    :member-order: bysource

wig.phys object
---------------

.. autoclass:: wig.phys.phys
    :members:
    :member-order: bysource

wig.source object
-----------------

.. autoclass:: wig.source.source
  :members:
  :member-order: bysource


.. autoclass: wig.source.dist
  :members:
  :member-order: bysource


wig.tally object
----------------

.. autoclass:: wig.tally.tally
    :members:
    :member-order: bysource

Run and Runtime Submodules
==========================


wig.runner object
-----------------

.. autoclass:: wig.runner.runner
    :members:
    :member-order: bysource

wig.mcnpdaemon object
---------------------

.. autoclass:: wig.mcnpdaemon.mcnpdaemon
    :members:
    :member-order: bysource

Post-processing Submodules
==========================

wig.analyze object
------------------

.. autoclass:: wig.analyze.analyze
    :members:
    :member-order: bysource

Convenience and internal submodules
===================================

wig.mcnp_string object
----------------------

.. autoclass:: wig.mcnp_string.mstring
    :members:
    :member-order: bysource
